### PR TITLE
Provides the option to not have a text message sent

### PR DESCRIPTION
**Pull request by dcm684**
Allows the user to not have a text message sent once a lower price has been found.

May not be useful in non-dev situations, but maybe the user cannot use twilio

### CODE REVIEW

**Comment by wcrasta** [comment]
Hi @dcm684, thanks for your PR and for taking interest in this project. I will review it when I have some time (most likely this weekend) and get back to you.

**Comment by wcrasta** [comment]
Hi @dcm684, I'm closing this PR because (imo) this program is only useful when used in tandem with Twilio, or some other instant notification service. Feel free to convince me otherwise.

**Comment by dcm684** [comment]
I feel that it is useful in several cases:

- Development when you don't need a text every time that you want to test some changes
- When the user has a phone plan that has only a limited number of texts per month
- When the user does not have a Twilio account and doesn't have one or if they have already used up their allotment of free messages.

If the program uses some sort of instant notification service by default, and crashes if the appropriate credentials aren't valid, there should be someway to deactivate it.

Maybe it would be more appropriate to have a different program argument where you can choose the notification system, e.g. --notification. Currently there would be only two options, twilio and none, with twilio being the default. Would that be better?

**Comment by wcrasta** [comment]
> If the program uses some sort of instant notification service by default, and crashes if the appropriate credentials aren't valid, there should be someway to deactivate it.

Fair enough. I suppose this deserves some consideration. I will review it within a few days. Thanks for your contribution!

**Review by wcrasta — APPROVED** [review]

**Pull request merged**
