### PR TITLE
Reddit Refactor

### PR DESCRIPTION
**Pull request by imjohsep**
Hey, I saw your post on Reddit today and decided to contribute a bit to your project. I hope these refactors make sense, but if you would like further clarification on anything comment on my PR. 

Otherwise, mergey merge!

Cheers,
Imjohsep

### CODE REVIEW

**Comment by ghost** [comment]
I am a hobbyist/beginner with Python and am interested in using this to learn a bit more.

Using git I have cloned the repoitry and successfully run the code (incl. Twilio). Im not sure though how to checkout the specific commit above from @imjohsep as Id like to test that too?

Apologies: I didt read properly, I have now forked!

**Comment by imjohsep** [comment]
@revren You can clone my forked version of this repo to get a version of the pull request (PR) on this thread. Just go [here](https://github.com/imjohsep/SWA-Scraper) and clone/download. Then, if you want to improve my PR you can fork my repo, make changes, push your changes to your fork, and  make a PR request against my repo. Good luck!

**Comment by wcrasta** [comment]
Thanks for the PR @imjohsep! I'm happy to see that you've found this project interesting. I'll take a look at the code soon.

**Comment by ghost** [comment]
Thanks very much for the guidance @imjohsep 

I have had a dig on my own fork, using the original branch. I have started to test a similar this approach for easyjet.com (European provider). @wcrasta obviously credit will be due for your approach - what are your thoughts on how I should share/use my code? Perhaps we could even combine efforts and have a config file for each flight provider?

**Comment by wcrasta** [comment]
Hey @revren, I'm glad you like the approach, and I'm thrilled that you've decided to do something similar with EasyJet. Since this project is advertised as a Southwest scraper, for now, I'd prefer it to leave it just for Southwest. However, once your project is up and running, I'd be open to linking to it from this repository's README!

**Comment by cjmarvin** [comment]
Hi @imjohsep, great work on the additions.  I was just wondering if there was any particular reason to use `optparse`? It has been deprecated since Python 3.2 and replaced with `argparse`.

**Comment by wcrasta** [comment]
@imjohsep, just had some time to review your PR and it was fantastic. Thanks for your contribution. Being new to Python myself, I learned a lot in terms of best practices from your refactoring. The code looks very neat/clean now.

I did make a few changes, but like @cjmarvin, I too am wondering about argparse vs. optparse. Thanks.

**Comment by imjohsep** [comment]
Good catch @cjmarvin. I work at a 2.7 shop, so didn't see that deprecation notice on 3.2. Luckily the syntax is relatively similar to optparse, so the switch was ezpz. see #6 

@wcrasta Thanks for merging! I like your usage of the ini file and configparser.

**Comment by imjohsep** [comment]
@revren I don't see any of your changes on your fork/repo. If you make a branch off of master and commit your code to that branch you can do a PR against your own master or one of our master branches to show your changes. I recommend pulling in @wcrasta's master branch into your fork to keep your fork up-to-date. You will likely have some merge conflicts if you have done a lot of work on your local version.

**Comment by cjmarvin** [comment]
No problemo @imjohsep, I also haven't fully bit the 3.x bullet (mostly work in science, so slowly migrating from 2.7 to 3.5+), so I know what you mean.

**Pull request merged**
