### PR TITLE
add a dict of SWA airport codes

### PR DESCRIPTION
**Pull request by nivintw**
I added a dictionary of valid airport codes and their lexical names as reported on www.southwest.com. 
I used Beautiful soup 4 to parse out the names, so everything should be here. 
I also added it as the choices keyword for the origin and destination so that there was some basic error checking there. 

Obviously, this will need to be updated if southwest adds an airport or removes an airport, but that won't happen often and the dict is easily editable now that it exists.

### CODE REVIEW

**Comment by wcrasta** [comment]
Hi @twn346, thank you for your PR! I'll take a look at your code this weekend and will merge it in then.

**Comment by nivintw** [comment]
Alright, no worries. It's just the one file so shouldn't take long at all.

**Comment by wcrasta** [comment]
Hi @twn346, I had a chance to look at your Pull Request. As I mentioned earlier, thank you for contributing. It means a lot to me that someone else found this project interesting enough to take time to contribute.

However, I'd like to keep the codebase simple and avoid unnecessary complexity in this project. While a list of airports might be useful in some scenarios, I imagine that anyone using this tool can look it up themselves without needing to use our command line feature.  As such, I have closed this pull request.

**Comment by nivintw** [comment]
,,, That's. Hey man, it's your project. I'm not exactly sure how a single dictionary is complex. At all. But it's your code.

**Pull request closed without merging**
