### PR TITLE
Added email functionality

### PR DESCRIPTION
**Pull request by sagar-shah**
2 new optional parameters have been added.
--email - Account that the user wants to use to send/receive email. Just 1 email is entered and it is used to send email to itself.
--password - Email account's password.

Notes:
Using this requires turning on access to less secure apps in the gmail account's settings.
See here: https://www.google.com/settings/security/lesssecureapps

Sample commands:
`python app.py --from HOU --to MDW --departure-date 05/12 --return-date 05/14 --passengers 2 --desired-total 215 --interval 1 --email myemail@gmail.com --password mypassword`

`python app.py --from HOU --to MDW --departure-date 05/12 --return-date 05/14 --passengers 2 --desired-total 215 --interval 1`

### CODE REVIEW

**Comment by wcrasta** [comment]
Hi @sagar-shah,
Thank you for submitting a PR! I didn't expect the project to get this much attention, and am truly grateful that someone wants to contribute. Thank you.

I like the idea of a user getting an e-mail when a deal is found, and thought about adding that functionality as well.  However, asking a user for their e-mail password (even if it's just into their own command-line script) is not something I think we should do. If there's alternate ways of sending an e-mail to the user without having him/her submit their e-mail password, that'd be great. 

Note: Please don't let this discourage you from submitting PR's in the future! Feel free to contact me to discuss potential features.

**Comment by sagar-shah** [comment]
Hi Warren,

In order for the email functionality to work, we need some email id to send
the emails. So if we can create something like notification@gmail.com, then
the user only has to enter his email id where he wants the email to be
received. For sending emails we can then use the notification@gmail.com id.
What do you think of this approach?

Thanks,
Sagar

**Comment by wcrasta** [comment]
That sounds like a good idea. However, would we have to store the password for notification@gmail.com ID in the source code?

**Comment by sagar-shah** [comment]
Yes, we would need to put the password in the source code. I am looking up
online to find out exactly what is the industry standard way of handling
this. I am sure out of all the open source softwares around, many must have
this functionality. We just need to see how they solved this problem.

**Comment by sagar-shah** [comment]
Check the below links:

http://stackoverflow.com/questions/20986212/how-to-use-python-to-send-email-without-exposing-password
http://stackoverflow.com/questions/25084907/what-is-a-secure-way-to-send-an-email-using-python-and-gmail-as-the-provider
http://stackoverflow.com/questions/31456217/mail-without-password-in-python

Taking the password from the user as input using the getpass module is one
option as mentioned in the above links.
Let me know your views.

-Sagar

**Comment by wcrasta** [comment]
Hey Sagar,

I'd like to completely stay away from asking a user for their password (whether through command line or through a prompt). I looked through those links, and it seemed to me that a common solution was to store the password as an environment variable. However, since this project is open-source, one way or another, we'd have to provide the password for the user to set the environment variable.

I wish there was a way where we could only ask the user for their e-mail AND we didn't have to specify the password for OUR notification e-mail in plaintext/through environment variables. Does that make sense?

**Pull request closed without merging**
